spring:
  mail:
    host: smtp.example.com
    port: 587
    username: vovecinema@gmail.com
    password: xvbzhervcksvtlhy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/template/
    suffix: .html
