spring:
  mail:
    host: smtp.example.com
    port: 587
    username: vovecinema@gmail.com
    password: xvbzhervcksvtlhy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/template/
    suffix: .html

server:
  ssl:
    key-store: classpath:vove.p12
    key-store-password: senha
    key-store-type: pkcs12
    key-alias: 1
    key-password: senha
  port: 8443