package sptech.school.voveaplication.service.filtroComentario;

import sptech.school.voveaplication.domain.comentario.Comentario;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class FiltroComentario {

    public static void filtrarPalavroes(Comentario comentario) {
        String[] palavrasNegadas = {
                "caralho",
                "karalho",
                "porra",
                "poha",
                "buceta",
                "puta",
                "puto",
                "capeta",
                "demonio",
                "vadia",
                "desgraçad",
                "vagabund",
                "piroc",
                "penis",
                "peniano",
                "pau",
                "giromba",
                "jéba",
                "jeba",
                "geba",
                "cacet",
                "piru",
                "bacanal",
                "pirok",
                "rapariga",
                "rampera",
                "rampeira",
                "macaco",
                "monkey",
                "pariu",
                "pererec",
                "bucetinh",
                "xota",
                "chota",
                "quenga",
                "kenga",
                "nazist",
                "racist",
                "pik",
                "pica",
                "picao",
                "picão",
                "nude",
                "fude",
                "fode",
                "xerec",
                "cherec",
                "cherek",
                "xerek",
                "piranh",
                "fodid",
                "prostitut",
                "cafagest",
                "cafajest",
                "cafetão",
                "cafetao",
                "pinto",
                "bilau",
                "bilal",
                "bilal",
                "piriquit",
                "pirikit",
                "xinbiu",
                "ximbiu",
                "chinbiu",
                "chimbiu",
                "morra",
                "morte",
                "disgraça",
                "desgraça",
                "boquete",
                "safad",
                "surub",
                "orgy",
                "orgia",
                "geromb",
                "jeromb",
                "transar",
                "tranza",
                "tranzar",
                "maconha",
                "crack",
                "lsd",
                "k9",
                "cocaína",
                "cocaina",
                "sex",
                "bunda",
                "gozo",
                "goso",
                "gosa",
                "bobo",
                "babaca",
                "babaka",
                "babaka",
                "rola",
                "buçanha",
                "piriquit",
                "bobão",
                "boba",
                "carai",
                "pirikit",
                "cuzinho",
                "cuzin",
                "putinh",
                "putinh",
                "goza",
                "cachorr",
                "patet",
                "caçaralho",
                "orgasm",
                "xvideos",
                "porhub",
                "cafajest",
                "cafagest",
                "kafagest",
                "kafajest",
                "cu ",
                "caralh",
                "jiromba",
                "peitud",
                "bumbum",
                "seu gordo",
                "rabetao",
                "ranbetão",
                "pintud",
                "bucetud",
                "rolud",
                "bucelandia",
                "garganta profunda",
                "raba",
                "otari",
                "idiot",
                "merda",
                "bosta",
                "chupa meu",
                "chupa minha",
                "senta na minha",
                "senta nas minha",
                "manda foto sem",
                "cueca",
                "meter",
                "chuca",
                "chuka",
                "xuca",
                "posso comer seu",
                "bundinh",
                "vou te comer",
                "hemorroida",
                "estupro",
                "estupr",
                "gay",
                "viadinho",
                "bixa",
                "boiola",
                "biba",
                "cabaço",
                "cabasso",
                "fimose",
                "assaltar",
                "ejacula",
                "ejacular",
                "molestar",
                "santos",
                "luxenburgo",
                "palmeiras"
        };

        for (String palavra : palavrasNegadas) {
            Pattern pattern = Pattern.compile("\\b" + palavra + "\\b", Pattern.CASE_INSENSITIVE);
            Matcher matcher = pattern.matcher(comentario.getDescricao());
            comentario.setDescricao(matcher.replaceAll("\\$&#@"));
        }
    }
}
